#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miniSmartCloudService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="minismart")]
	public partial class miniSmartDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttab_CA_EMS_FREEZEFRAME_DATA(tab_CA_EMS_FREEZEFRAME_DATA instance);
    partial void Updatetab_CA_EMS_FREEZEFRAME_DATA(tab_CA_EMS_FREEZEFRAME_DATA instance);
    partial void Deletetab_CA_EMS_FREEZEFRAME_DATA(tab_CA_EMS_FREEZEFRAME_DATA instance);
    partial void Inserttab_m_VCI_REGISTERATION(tab_m_VCI_REGISTERATION instance);
    partial void Updatetab_m_VCI_REGISTERATION(tab_m_VCI_REGISTERATION instance);
    partial void Deletetab_m_VCI_REGISTERATION(tab_m_VCI_REGISTERATION instance);
    partial void Inserttab_m_DEVICE_VIN_MAPPING(tab_m_DEVICE_VIN_MAPPING instance);
    partial void Updatetab_m_DEVICE_VIN_MAPPING(tab_m_DEVICE_VIN_MAPPING instance);
    partial void Deletetab_m_DEVICE_VIN_MAPPING(tab_m_DEVICE_VIN_MAPPING instance);
    partial void Inserttab_CA_EMS_DTC_INFO(tab_CA_EMS_DTC_INFO instance);
    partial void Updatetab_CA_EMS_DTC_INFO(tab_CA_EMS_DTC_INFO instance);
    partial void Deletetab_CA_EMS_DTC_INFO(tab_CA_EMS_DTC_INFO instance);
    partial void Inserttab_CA_EMS_MASTER_INFO(tab_CA_EMS_MASTER_INFO instance);
    partial void Updatetab_CA_EMS_MASTER_INFO(tab_CA_EMS_MASTER_INFO instance);
    partial void Deletetab_CA_EMS_MASTER_INFO(tab_CA_EMS_MASTER_INFO instance);
    partial void Inserttab_CA_CRITICAL_DTC_ADD(tab_CA_CRITICAL_DTC_ADD instance);
    partial void Updatetab_CA_CRITICAL_DTC_ADD(tab_CA_CRITICAL_DTC_ADD instance);
    partial void Deletetab_CA_CRITICAL_DTC_ADD(tab_CA_CRITICAL_DTC_ADD instance);
    partial void Inserttab_CA_EMS_DTC_LOGIC_ADD(tab_CA_EMS_DTC_LOGIC_ADD instance);
    partial void Updatetab_CA_EMS_DTC_LOGIC_ADD(tab_CA_EMS_DTC_LOGIC_ADD instance);
    partial void Deletetab_CA_EMS_DTC_LOGIC_ADD(tab_CA_EMS_DTC_LOGIC_ADD instance);
    partial void Inserttab_CA_EMS_DTC_LOGIC_BUILD(tab_CA_EMS_DTC_LOGIC_BUILD instance);
    partial void Updatetab_CA_EMS_DTC_LOGIC_BUILD(tab_CA_EMS_DTC_LOGIC_BUILD instance);
    partial void Deletetab_CA_EMS_DTC_LOGIC_BUILD(tab_CA_EMS_DTC_LOGIC_BUILD instance);
    partial void Inserttab_m_ADMIN_USER(tab_m_ADMIN_USER instance);
    partial void Updatetab_m_ADMIN_USER(tab_m_ADMIN_USER instance);
    partial void Deletetab_m_ADMIN_USER(tab_m_ADMIN_USER instance);
    partial void Inserttab_m_VIN_SCORE(tab_m_VIN_SCORE instance);
    partial void Updatetab_m_VIN_SCORE(tab_m_VIN_SCORE instance);
    partial void Deletetab_m_VIN_SCORE(tab_m_VIN_SCORE instance);
    #endregion
		
		public miniSmartDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Cloud_ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public miniSmartDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public miniSmartDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public miniSmartDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public miniSmartDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tab_CA_EMS_FREEZEFRAME_DATA> tab_CA_EMS_FREEZEFRAME_DATAs
		{
			get
			{
				return this.GetTable<tab_CA_EMS_FREEZEFRAME_DATA>();
			}
		}
		
		public System.Data.Linq.Table<tab_m_VCI_REGISTERATION> tab_m_VCI_REGISTERATIONs
		{
			get
			{
				return this.GetTable<tab_m_VCI_REGISTERATION>();
			}
		}
		
		public System.Data.Linq.Table<tab_m_DEVICE_VIN_MAPPING> tab_m_DEVICE_VIN_MAPPINGs
		{
			get
			{
				return this.GetTable<tab_m_DEVICE_VIN_MAPPING>();
			}
		}
		
		public System.Data.Linq.Table<tab_CA_EMS_DTC_INFO> tab_CA_EMS_DTC_INFOs
		{
			get
			{
				return this.GetTable<tab_CA_EMS_DTC_INFO>();
			}
		}
		
		public System.Data.Linq.Table<tab_CA_EMS_MASTER_INFO> tab_CA_EMS_MASTER_INFOs
		{
			get
			{
				return this.GetTable<tab_CA_EMS_MASTER_INFO>();
			}
		}
		
		public System.Data.Linq.Table<tab_CA_CRITICAL_DTC_ADD> tab_CA_CRITICAL_DTC_ADDs
		{
			get
			{
				return this.GetTable<tab_CA_CRITICAL_DTC_ADD>();
			}
		}
		
		public System.Data.Linq.Table<tab_CA_EMS_DTC_LOGIC_ADD> tab_CA_EMS_DTC_LOGIC_ADDs
		{
			get
			{
				return this.GetTable<tab_CA_EMS_DTC_LOGIC_ADD>();
			}
		}
		
		public System.Data.Linq.Table<tab_CA_EMS_DTC_LOGIC_BUILD> tab_CA_EMS_DTC_LOGIC_BUILDs
		{
			get
			{
				return this.GetTable<tab_CA_EMS_DTC_LOGIC_BUILD>();
			}
		}
		
		public System.Data.Linq.Table<tab_m_ADMIN_USER> tab_m_ADMIN_USERs
		{
			get
			{
				return this.GetTable<tab_m_ADMIN_USER>();
			}
		}
		
		public System.Data.Linq.Table<tab_m_VIN_SCORE> tab_m_VIN_SCOREs
		{
			get
			{
				return this.GetTable<tab_m_VIN_SCORE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_EMS_FREEZEFRAME_DATA")]
	public partial class tab_CA_EMS_FREEZEFRAME_DATA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _freeze_ID;
		
		private int _master_ID;
		
		private int _dtc_INFO_ID;
		
		private string _freeze_SIGNAL;
		
		private string _freeze_VALUE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfreeze_IDChanging(int value);
    partial void Onfreeze_IDChanged();
    partial void Onmaster_IDChanging(int value);
    partial void Onmaster_IDChanged();
    partial void Ondtc_INFO_IDChanging(int value);
    partial void Ondtc_INFO_IDChanged();
    partial void Onfreeze_SIGNALChanging(string value);
    partial void Onfreeze_SIGNALChanged();
    partial void Onfreeze_VALUEChanging(string value);
    partial void Onfreeze_VALUEChanged();
    #endregion
		
		public tab_CA_EMS_FREEZEFRAME_DATA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int freeze_ID
		{
			get
			{
				return this._freeze_ID;
			}
			set
			{
				if ((this._freeze_ID != value))
				{
					this.Onfreeze_IDChanging(value);
					this.SendPropertyChanging();
					this._freeze_ID = value;
					this.SendPropertyChanged("freeze_ID");
					this.Onfreeze_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_master_ID", DbType="Int NOT NULL")]
		public int master_ID
		{
			get
			{
				return this._master_ID;
			}
			set
			{
				if ((this._master_ID != value))
				{
					this.Onmaster_IDChanging(value);
					this.SendPropertyChanging();
					this._master_ID = value;
					this.SendPropertyChanged("master_ID");
					this.Onmaster_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_INFO_ID", DbType="Int NOT NULL")]
		public int dtc_INFO_ID
		{
			get
			{
				return this._dtc_INFO_ID;
			}
			set
			{
				if ((this._dtc_INFO_ID != value))
				{
					this.Ondtc_INFO_IDChanging(value);
					this.SendPropertyChanging();
					this._dtc_INFO_ID = value;
					this.SendPropertyChanged("dtc_INFO_ID");
					this.Ondtc_INFO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_SIGNAL", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string freeze_SIGNAL
		{
			get
			{
				return this._freeze_SIGNAL;
			}
			set
			{
				if ((this._freeze_SIGNAL != value))
				{
					this.Onfreeze_SIGNALChanging(value);
					this.SendPropertyChanging();
					this._freeze_SIGNAL = value;
					this.SendPropertyChanged("freeze_SIGNAL");
					this.Onfreeze_SIGNALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_VALUE", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string freeze_VALUE
		{
			get
			{
				return this._freeze_VALUE;
			}
			set
			{
				if ((this._freeze_VALUE != value))
				{
					this.Onfreeze_VALUEChanging(value);
					this.SendPropertyChanging();
					this._freeze_VALUE = value;
					this.SendPropertyChanged("freeze_VALUE");
					this.Onfreeze_VALUEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_m_VCI_REGISTERATION")]
	public partial class tab_m_VCI_REGISTERATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _register_ID_PK;
		
		private string _register_MOBILE_DEVICE_ID;
		
		private string _register_VCI_ID;
		
		private string _register_ID;
		
		private string _register_COTEK_ID;
		
		private string _register_FIRST_NAME;
		
		private string _register_LAST_NAME;
		
		private string _register_IS_ACTIVE;
		
		private string _register_USER_TYPE;
		
		private string _register_SKILL_ID;
		
		private string _register_SKILL_NAME;
		
		private string _register_USER_TYPE_DESC;
		
		private string _register_PASSWORD_CHANGED;
		
		private string _register_AREA_NAME;
		
		private string _register_ZONE;
		
		private string _register_CODE;
		
		private string _register_LOCATION_NAME;
		
		private string _register_CHANNEL_NO;
		
		private string _register_IS_LDAP__AUTHENDICATED;
		
		private string _register_LM_COMPANY_NAME;
		
		private string _register_LM_LOCATION;
		
		private string _register_LM_OWNER_NAME;
		
		private string _register_LM_MOBILE_NO;
		
		private System.DateTime _register_DATE;
		
		private string _register_DEALER_NAME;
		
		private string _register_APP_VERSION;
		
		private string _register_SERIAL_NUMBER;
		
		private string _register_DEVICE_TOKEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onregister_ID_PKChanging(int value);
    partial void Onregister_ID_PKChanged();
    partial void Onregister_MOBILE_DEVICE_IDChanging(string value);
    partial void Onregister_MOBILE_DEVICE_IDChanged();
    partial void Onregister_VCI_IDChanging(string value);
    partial void Onregister_VCI_IDChanged();
    partial void Onregister_IDChanging(string value);
    partial void Onregister_IDChanged();
    partial void Onregister_COTEK_IDChanging(string value);
    partial void Onregister_COTEK_IDChanged();
    partial void Onregister_FIRST_NAMEChanging(string value);
    partial void Onregister_FIRST_NAMEChanged();
    partial void Onregister_LAST_NAMEChanging(string value);
    partial void Onregister_LAST_NAMEChanged();
    partial void Onregister_IS_ACTIVEChanging(string value);
    partial void Onregister_IS_ACTIVEChanged();
    partial void Onregister_USER_TYPEChanging(string value);
    partial void Onregister_USER_TYPEChanged();
    partial void Onregister_SKILL_IDChanging(string value);
    partial void Onregister_SKILL_IDChanged();
    partial void Onregister_SKILL_NAMEChanging(string value);
    partial void Onregister_SKILL_NAMEChanged();
    partial void Onregister_USER_TYPE_DESCChanging(string value);
    partial void Onregister_USER_TYPE_DESCChanged();
    partial void Onregister_PASSWORD_CHANGEDChanging(string value);
    partial void Onregister_PASSWORD_CHANGEDChanged();
    partial void Onregister_AREA_NAMEChanging(string value);
    partial void Onregister_AREA_NAMEChanged();
    partial void Onregister_ZONEChanging(string value);
    partial void Onregister_ZONEChanged();
    partial void Onregister_CODEChanging(string value);
    partial void Onregister_CODEChanged();
    partial void Onregister_LOCATION_NAMEChanging(string value);
    partial void Onregister_LOCATION_NAMEChanged();
    partial void Onregister_CHANNEL_NOChanging(string value);
    partial void Onregister_CHANNEL_NOChanged();
    partial void Onregister_IS_LDAP__AUTHENDICATEDChanging(string value);
    partial void Onregister_IS_LDAP__AUTHENDICATEDChanged();
    partial void Onregister_LM_COMPANY_NAMEChanging(string value);
    partial void Onregister_LM_COMPANY_NAMEChanged();
    partial void Onregister_LM_LOCATIONChanging(string value);
    partial void Onregister_LM_LOCATIONChanged();
    partial void Onregister_LM_OWNER_NAMEChanging(string value);
    partial void Onregister_LM_OWNER_NAMEChanged();
    partial void Onregister_LM_MOBILE_NOChanging(string value);
    partial void Onregister_LM_MOBILE_NOChanged();
    partial void Onregister_DATEChanging(System.DateTime value);
    partial void Onregister_DATEChanged();
    partial void Onregister_DEALER_NAMEChanging(string value);
    partial void Onregister_DEALER_NAMEChanged();
    partial void Onregister_APP_VERSIONChanging(string value);
    partial void Onregister_APP_VERSIONChanged();
    partial void Onregister_SERIAL_NUMBERChanging(string value);
    partial void Onregister_SERIAL_NUMBERChanged();
    partial void Onregister_DEVICE_TOKENChanging(string value);
    partial void Onregister_DEVICE_TOKENChanged();
    #endregion
		
		public tab_m_VCI_REGISTERATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_ID_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int register_ID_PK
		{
			get
			{
				return this._register_ID_PK;
			}
			set
			{
				if ((this._register_ID_PK != value))
				{
					this.Onregister_ID_PKChanging(value);
					this.SendPropertyChanging();
					this._register_ID_PK = value;
					this.SendPropertyChanged("register_ID_PK");
					this.Onregister_ID_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_MOBILE_DEVICE_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string register_MOBILE_DEVICE_ID
		{
			get
			{
				return this._register_MOBILE_DEVICE_ID;
			}
			set
			{
				if ((this._register_MOBILE_DEVICE_ID != value))
				{
					this.Onregister_MOBILE_DEVICE_IDChanging(value);
					this.SendPropertyChanging();
					this._register_MOBILE_DEVICE_ID = value;
					this.SendPropertyChanged("register_MOBILE_DEVICE_ID");
					this.Onregister_MOBILE_DEVICE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_VCI_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_VCI_ID
		{
			get
			{
				return this._register_VCI_ID;
			}
			set
			{
				if ((this._register_VCI_ID != value))
				{
					this.Onregister_VCI_IDChanging(value);
					this.SendPropertyChanging();
					this._register_VCI_ID = value;
					this.SendPropertyChanged("register_VCI_ID");
					this.Onregister_VCI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_ID
		{
			get
			{
				return this._register_ID;
			}
			set
			{
				if ((this._register_ID != value))
				{
					this.Onregister_IDChanging(value);
					this.SendPropertyChanging();
					this._register_ID = value;
					this.SendPropertyChanged("register_ID");
					this.Onregister_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_COTEK_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_COTEK_ID
		{
			get
			{
				return this._register_COTEK_ID;
			}
			set
			{
				if ((this._register_COTEK_ID != value))
				{
					this.Onregister_COTEK_IDChanging(value);
					this.SendPropertyChanging();
					this._register_COTEK_ID = value;
					this.SendPropertyChanged("register_COTEK_ID");
					this.Onregister_COTEK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_FIRST_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string register_FIRST_NAME
		{
			get
			{
				return this._register_FIRST_NAME;
			}
			set
			{
				if ((this._register_FIRST_NAME != value))
				{
					this.Onregister_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_FIRST_NAME = value;
					this.SendPropertyChanged("register_FIRST_NAME");
					this.Onregister_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LAST_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string register_LAST_NAME
		{
			get
			{
				return this._register_LAST_NAME;
			}
			set
			{
				if ((this._register_LAST_NAME != value))
				{
					this.Onregister_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_LAST_NAME = value;
					this.SendPropertyChanged("register_LAST_NAME");
					this.Onregister_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_IS_ACTIVE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_IS_ACTIVE
		{
			get
			{
				return this._register_IS_ACTIVE;
			}
			set
			{
				if ((this._register_IS_ACTIVE != value))
				{
					this.Onregister_IS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._register_IS_ACTIVE = value;
					this.SendPropertyChanged("register_IS_ACTIVE");
					this.Onregister_IS_ACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_USER_TYPE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_USER_TYPE
		{
			get
			{
				return this._register_USER_TYPE;
			}
			set
			{
				if ((this._register_USER_TYPE != value))
				{
					this.Onregister_USER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._register_USER_TYPE = value;
					this.SendPropertyChanged("register_USER_TYPE");
					this.Onregister_USER_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_SKILL_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_SKILL_ID
		{
			get
			{
				return this._register_SKILL_ID;
			}
			set
			{
				if ((this._register_SKILL_ID != value))
				{
					this.Onregister_SKILL_IDChanging(value);
					this.SendPropertyChanging();
					this._register_SKILL_ID = value;
					this.SendPropertyChanged("register_SKILL_ID");
					this.Onregister_SKILL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_SKILL_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string register_SKILL_NAME
		{
			get
			{
				return this._register_SKILL_NAME;
			}
			set
			{
				if ((this._register_SKILL_NAME != value))
				{
					this.Onregister_SKILL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_SKILL_NAME = value;
					this.SendPropertyChanged("register_SKILL_NAME");
					this.Onregister_SKILL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_USER_TYPE_DESC", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string register_USER_TYPE_DESC
		{
			get
			{
				return this._register_USER_TYPE_DESC;
			}
			set
			{
				if ((this._register_USER_TYPE_DESC != value))
				{
					this.Onregister_USER_TYPE_DESCChanging(value);
					this.SendPropertyChanging();
					this._register_USER_TYPE_DESC = value;
					this.SendPropertyChanged("register_USER_TYPE_DESC");
					this.Onregister_USER_TYPE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_PASSWORD_CHANGED", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_PASSWORD_CHANGED
		{
			get
			{
				return this._register_PASSWORD_CHANGED;
			}
			set
			{
				if ((this._register_PASSWORD_CHANGED != value))
				{
					this.Onregister_PASSWORD_CHANGEDChanging(value);
					this.SendPropertyChanging();
					this._register_PASSWORD_CHANGED = value;
					this.SendPropertyChanged("register_PASSWORD_CHANGED");
					this.Onregister_PASSWORD_CHANGEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_AREA_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string register_AREA_NAME
		{
			get
			{
				return this._register_AREA_NAME;
			}
			set
			{
				if ((this._register_AREA_NAME != value))
				{
					this.Onregister_AREA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_AREA_NAME = value;
					this.SendPropertyChanged("register_AREA_NAME");
					this.Onregister_AREA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_ZONE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string register_ZONE
		{
			get
			{
				return this._register_ZONE;
			}
			set
			{
				if ((this._register_ZONE != value))
				{
					this.Onregister_ZONEChanging(value);
					this.SendPropertyChanging();
					this._register_ZONE = value;
					this.SendPropertyChanged("register_ZONE");
					this.Onregister_ZONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string register_CODE
		{
			get
			{
				return this._register_CODE;
			}
			set
			{
				if ((this._register_CODE != value))
				{
					this.Onregister_CODEChanging(value);
					this.SendPropertyChanging();
					this._register_CODE = value;
					this.SendPropertyChanged("register_CODE");
					this.Onregister_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LOCATION_NAME", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string register_LOCATION_NAME
		{
			get
			{
				return this._register_LOCATION_NAME;
			}
			set
			{
				if ((this._register_LOCATION_NAME != value))
				{
					this.Onregister_LOCATION_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_LOCATION_NAME = value;
					this.SendPropertyChanged("register_LOCATION_NAME");
					this.Onregister_LOCATION_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_CHANNEL_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string register_CHANNEL_NO
		{
			get
			{
				return this._register_CHANNEL_NO;
			}
			set
			{
				if ((this._register_CHANNEL_NO != value))
				{
					this.Onregister_CHANNEL_NOChanging(value);
					this.SendPropertyChanging();
					this._register_CHANNEL_NO = value;
					this.SendPropertyChanged("register_CHANNEL_NO");
					this.Onregister_CHANNEL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_IS_LDAP__AUTHENDICATED", DbType="NVarChar(20)")]
		public string register_IS_LDAP__AUTHENDICATED
		{
			get
			{
				return this._register_IS_LDAP__AUTHENDICATED;
			}
			set
			{
				if ((this._register_IS_LDAP__AUTHENDICATED != value))
				{
					this.Onregister_IS_LDAP__AUTHENDICATEDChanging(value);
					this.SendPropertyChanging();
					this._register_IS_LDAP__AUTHENDICATED = value;
					this.SendPropertyChanged("register_IS_LDAP__AUTHENDICATED");
					this.Onregister_IS_LDAP__AUTHENDICATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LM_COMPANY_NAME", DbType="NVarChar(250)")]
		public string register_LM_COMPANY_NAME
		{
			get
			{
				return this._register_LM_COMPANY_NAME;
			}
			set
			{
				if ((this._register_LM_COMPANY_NAME != value))
				{
					this.Onregister_LM_COMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_LM_COMPANY_NAME = value;
					this.SendPropertyChanged("register_LM_COMPANY_NAME");
					this.Onregister_LM_COMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LM_LOCATION", DbType="NVarChar(50)")]
		public string register_LM_LOCATION
		{
			get
			{
				return this._register_LM_LOCATION;
			}
			set
			{
				if ((this._register_LM_LOCATION != value))
				{
					this.Onregister_LM_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._register_LM_LOCATION = value;
					this.SendPropertyChanged("register_LM_LOCATION");
					this.Onregister_LM_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LM_OWNER_NAME", DbType="NVarChar(50)")]
		public string register_LM_OWNER_NAME
		{
			get
			{
				return this._register_LM_OWNER_NAME;
			}
			set
			{
				if ((this._register_LM_OWNER_NAME != value))
				{
					this.Onregister_LM_OWNER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_LM_OWNER_NAME = value;
					this.SendPropertyChanged("register_LM_OWNER_NAME");
					this.Onregister_LM_OWNER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_LM_MOBILE_NO", DbType="NVarChar(20)")]
		public string register_LM_MOBILE_NO
		{
			get
			{
				return this._register_LM_MOBILE_NO;
			}
			set
			{
				if ((this._register_LM_MOBILE_NO != value))
				{
					this.Onregister_LM_MOBILE_NOChanging(value);
					this.SendPropertyChanging();
					this._register_LM_MOBILE_NO = value;
					this.SendPropertyChanged("register_LM_MOBILE_NO");
					this.Onregister_LM_MOBILE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime register_DATE
		{
			get
			{
				return this._register_DATE;
			}
			set
			{
				if ((this._register_DATE != value))
				{
					this.Onregister_DATEChanging(value);
					this.SendPropertyChanging();
					this._register_DATE = value;
					this.SendPropertyChanged("register_DATE");
					this.Onregister_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_DEALER_NAME", DbType="NVarChar(MAX)")]
		public string register_DEALER_NAME
		{
			get
			{
				return this._register_DEALER_NAME;
			}
			set
			{
				if ((this._register_DEALER_NAME != value))
				{
					this.Onregister_DEALER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._register_DEALER_NAME = value;
					this.SendPropertyChanged("register_DEALER_NAME");
					this.Onregister_DEALER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_APP_VERSION", DbType="NVarChar(10)")]
		public string register_APP_VERSION
		{
			get
			{
				return this._register_APP_VERSION;
			}
			set
			{
				if ((this._register_APP_VERSION != value))
				{
					this.Onregister_APP_VERSIONChanging(value);
					this.SendPropertyChanging();
					this._register_APP_VERSION = value;
					this.SendPropertyChanged("register_APP_VERSION");
					this.Onregister_APP_VERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_SERIAL_NUMBER", DbType="NVarChar(50)")]
		public string register_SERIAL_NUMBER
		{
			get
			{
				return this._register_SERIAL_NUMBER;
			}
			set
			{
				if ((this._register_SERIAL_NUMBER != value))
				{
					this.Onregister_SERIAL_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._register_SERIAL_NUMBER = value;
					this.SendPropertyChanged("register_SERIAL_NUMBER");
					this.Onregister_SERIAL_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_register_DEVICE_TOKEN", DbType="NVarChar(MAX)")]
		public string register_DEVICE_TOKEN
		{
			get
			{
				return this._register_DEVICE_TOKEN;
			}
			set
			{
				if ((this._register_DEVICE_TOKEN != value))
				{
					this.Onregister_DEVICE_TOKENChanging(value);
					this.SendPropertyChanging();
					this._register_DEVICE_TOKEN = value;
					this.SendPropertyChanged("register_DEVICE_TOKEN");
					this.Onregister_DEVICE_TOKENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_m_DEVICE_VIN_MAPPING")]
	public partial class tab_m_DEVICE_VIN_MAPPING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mapping_ID;
		
		private string _VIN_NUMBER;
		
		private string _device_TOKEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmapping_IDChanging(int value);
    partial void Onmapping_IDChanged();
    partial void OnVIN_NUMBERChanging(string value);
    partial void OnVIN_NUMBERChanged();
    partial void Ondevice_TOKENChanging(string value);
    partial void Ondevice_TOKENChanged();
    #endregion
		
		public tab_m_DEVICE_VIN_MAPPING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapping_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mapping_ID
		{
			get
			{
				return this._mapping_ID;
			}
			set
			{
				if ((this._mapping_ID != value))
				{
					this.Onmapping_IDChanging(value);
					this.SendPropertyChanging();
					this._mapping_ID = value;
					this.SendPropertyChanged("mapping_ID");
					this.Onmapping_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIN_NUMBER", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VIN_NUMBER
		{
			get
			{
				return this._VIN_NUMBER;
			}
			set
			{
				if ((this._VIN_NUMBER != value))
				{
					this.OnVIN_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._VIN_NUMBER = value;
					this.SendPropertyChanged("VIN_NUMBER");
					this.OnVIN_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_TOKEN", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string device_TOKEN
		{
			get
			{
				return this._device_TOKEN;
			}
			set
			{
				if ((this._device_TOKEN != value))
				{
					this.Ondevice_TOKENChanging(value);
					this.SendPropertyChanging();
					this._device_TOKEN = value;
					this.SendPropertyChanged("device_TOKEN");
					this.Ondevice_TOKENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_EMS_DTC_INFO")]
	public partial class tab_CA_EMS_DTC_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtc_ID;
		
		private int _freeze_MASTER_ID;
		
		private string _freeze_DTC_CODE;
		
		private string _freeze_DTC_DESCRIPTION;
		
		private string _freeze_DTC_STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondtc_IDChanging(int value);
    partial void Ondtc_IDChanged();
    partial void Onfreeze_MASTER_IDChanging(int value);
    partial void Onfreeze_MASTER_IDChanged();
    partial void Onfreeze_DTC_CODEChanging(string value);
    partial void Onfreeze_DTC_CODEChanged();
    partial void Onfreeze_DTC_DESCRIPTIONChanging(string value);
    partial void Onfreeze_DTC_DESCRIPTIONChanged();
    partial void Onfreeze_DTC_STATUSChanging(string value);
    partial void Onfreeze_DTC_STATUSChanged();
    #endregion
		
		public tab_CA_EMS_DTC_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtc_ID
		{
			get
			{
				return this._dtc_ID;
			}
			set
			{
				if ((this._dtc_ID != value))
				{
					this.Ondtc_IDChanging(value);
					this.SendPropertyChanging();
					this._dtc_ID = value;
					this.SendPropertyChanged("dtc_ID");
					this.Ondtc_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_MASTER_ID", DbType="Int NOT NULL")]
		public int freeze_MASTER_ID
		{
			get
			{
				return this._freeze_MASTER_ID;
			}
			set
			{
				if ((this._freeze_MASTER_ID != value))
				{
					this.Onfreeze_MASTER_IDChanging(value);
					this.SendPropertyChanging();
					this._freeze_MASTER_ID = value;
					this.SendPropertyChanged("freeze_MASTER_ID");
					this.Onfreeze_MASTER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_DTC_CODE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string freeze_DTC_CODE
		{
			get
			{
				return this._freeze_DTC_CODE;
			}
			set
			{
				if ((this._freeze_DTC_CODE != value))
				{
					this.Onfreeze_DTC_CODEChanging(value);
					this.SendPropertyChanging();
					this._freeze_DTC_CODE = value;
					this.SendPropertyChanged("freeze_DTC_CODE");
					this.Onfreeze_DTC_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_DTC_DESCRIPTION", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string freeze_DTC_DESCRIPTION
		{
			get
			{
				return this._freeze_DTC_DESCRIPTION;
			}
			set
			{
				if ((this._freeze_DTC_DESCRIPTION != value))
				{
					this.Onfreeze_DTC_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._freeze_DTC_DESCRIPTION = value;
					this.SendPropertyChanged("freeze_DTC_DESCRIPTION");
					this.Onfreeze_DTC_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_DTC_STATUS", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string freeze_DTC_STATUS
		{
			get
			{
				return this._freeze_DTC_STATUS;
			}
			set
			{
				if ((this._freeze_DTC_STATUS != value))
				{
					this.Onfreeze_DTC_STATUSChanging(value);
					this.SendPropertyChanging();
					this._freeze_DTC_STATUS = value;
					this.SendPropertyChanged("freeze_DTC_STATUS");
					this.Onfreeze_DTC_STATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_EMS_MASTER_INFO")]
	public partial class tab_CA_EMS_MASTER_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _freeze_MASTER_ID;
		
		private string _freeze_VIN_NUMBER;
		
		private string _freeze_MOBILE_NUMBER;
		
		private string _freeze_LATITUDE;
		
		private string _freeze_LONGITUDE;
		
		private System.DateTime _freeze_TIMESTAMP;
		
		private System.DateTime _freeze_UPDATEDON;
		
		private string _freeze_ECUNAME;
		
		private string _freeze_VEHICLENAME;
		
		private string _freeze_LOGINID;
		
		private string _freeze_LOGINNAME;
		
		private string _freeze_MOBILE_MAC_ADDRESS;
		
		private string _freeze_VCIID;
		
		private string _freeze_APP_VERSION;
		
		private string _freeze_DEALER_NAME;
		
		private string _freeze_AREA;
		
		private string _freeze_LOCATION;
		
		private string _freeze_SOURCE;
		
		private string _freeze_ODOValue;
		
		private System.Nullable<bool> _freeze_PUSH_NOTIFY;
		
		private System.Nullable<int> _freeze_NOTIFY_COUNTER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfreeze_MASTER_IDChanging(int value);
    partial void Onfreeze_MASTER_IDChanged();
    partial void Onfreeze_VIN_NUMBERChanging(string value);
    partial void Onfreeze_VIN_NUMBERChanged();
    partial void Onfreeze_MOBILE_NUMBERChanging(string value);
    partial void Onfreeze_MOBILE_NUMBERChanged();
    partial void Onfreeze_LATITUDEChanging(string value);
    partial void Onfreeze_LATITUDEChanged();
    partial void Onfreeze_LONGITUDEChanging(string value);
    partial void Onfreeze_LONGITUDEChanged();
    partial void Onfreeze_TIMESTAMPChanging(System.DateTime value);
    partial void Onfreeze_TIMESTAMPChanged();
    partial void Onfreeze_UPDATEDONChanging(System.DateTime value);
    partial void Onfreeze_UPDATEDONChanged();
    partial void Onfreeze_ECUNAMEChanging(string value);
    partial void Onfreeze_ECUNAMEChanged();
    partial void Onfreeze_VEHICLENAMEChanging(string value);
    partial void Onfreeze_VEHICLENAMEChanged();
    partial void Onfreeze_LOGINIDChanging(string value);
    partial void Onfreeze_LOGINIDChanged();
    partial void Onfreeze_LOGINNAMEChanging(string value);
    partial void Onfreeze_LOGINNAMEChanged();
    partial void Onfreeze_MOBILE_MAC_ADDRESSChanging(string value);
    partial void Onfreeze_MOBILE_MAC_ADDRESSChanged();
    partial void Onfreeze_VCIIDChanging(string value);
    partial void Onfreeze_VCIIDChanged();
    partial void Onfreeze_APP_VERSIONChanging(string value);
    partial void Onfreeze_APP_VERSIONChanged();
    partial void Onfreeze_DEALER_NAMEChanging(string value);
    partial void Onfreeze_DEALER_NAMEChanged();
    partial void Onfreeze_AREAChanging(string value);
    partial void Onfreeze_AREAChanged();
    partial void Onfreeze_LOCATIONChanging(string value);
    partial void Onfreeze_LOCATIONChanged();
    partial void Onfreeze_SOURCEChanging(string value);
    partial void Onfreeze_SOURCEChanged();
    partial void Onfreeze_ODOValueChanging(string value);
    partial void Onfreeze_ODOValueChanged();
    partial void Onfreeze_PUSH_NOTIFYChanging(System.Nullable<bool> value);
    partial void Onfreeze_PUSH_NOTIFYChanged();
    partial void Onfreeze_NOTIFY_COUNTERChanging(System.Nullable<int> value);
    partial void Onfreeze_NOTIFY_COUNTERChanged();
    #endregion
		
		public tab_CA_EMS_MASTER_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_MASTER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int freeze_MASTER_ID
		{
			get
			{
				return this._freeze_MASTER_ID;
			}
			set
			{
				if ((this._freeze_MASTER_ID != value))
				{
					this.Onfreeze_MASTER_IDChanging(value);
					this.SendPropertyChanging();
					this._freeze_MASTER_ID = value;
					this.SendPropertyChanged("freeze_MASTER_ID");
					this.Onfreeze_MASTER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_VIN_NUMBER", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string freeze_VIN_NUMBER
		{
			get
			{
				return this._freeze_VIN_NUMBER;
			}
			set
			{
				if ((this._freeze_VIN_NUMBER != value))
				{
					this.Onfreeze_VIN_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._freeze_VIN_NUMBER = value;
					this.SendPropertyChanged("freeze_VIN_NUMBER");
					this.Onfreeze_VIN_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_MOBILE_NUMBER", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string freeze_MOBILE_NUMBER
		{
			get
			{
				return this._freeze_MOBILE_NUMBER;
			}
			set
			{
				if ((this._freeze_MOBILE_NUMBER != value))
				{
					this.Onfreeze_MOBILE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._freeze_MOBILE_NUMBER = value;
					this.SendPropertyChanged("freeze_MOBILE_NUMBER");
					this.Onfreeze_MOBILE_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_LATITUDE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string freeze_LATITUDE
		{
			get
			{
				return this._freeze_LATITUDE;
			}
			set
			{
				if ((this._freeze_LATITUDE != value))
				{
					this.Onfreeze_LATITUDEChanging(value);
					this.SendPropertyChanging();
					this._freeze_LATITUDE = value;
					this.SendPropertyChanged("freeze_LATITUDE");
					this.Onfreeze_LATITUDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_LONGITUDE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string freeze_LONGITUDE
		{
			get
			{
				return this._freeze_LONGITUDE;
			}
			set
			{
				if ((this._freeze_LONGITUDE != value))
				{
					this.Onfreeze_LONGITUDEChanging(value);
					this.SendPropertyChanging();
					this._freeze_LONGITUDE = value;
					this.SendPropertyChanged("freeze_LONGITUDE");
					this.Onfreeze_LONGITUDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime freeze_TIMESTAMP
		{
			get
			{
				return this._freeze_TIMESTAMP;
			}
			set
			{
				if ((this._freeze_TIMESTAMP != value))
				{
					this.Onfreeze_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._freeze_TIMESTAMP = value;
					this.SendPropertyChanged("freeze_TIMESTAMP");
					this.Onfreeze_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_UPDATEDON", DbType="DateTime NOT NULL")]
		public System.DateTime freeze_UPDATEDON
		{
			get
			{
				return this._freeze_UPDATEDON;
			}
			set
			{
				if ((this._freeze_UPDATEDON != value))
				{
					this.Onfreeze_UPDATEDONChanging(value);
					this.SendPropertyChanging();
					this._freeze_UPDATEDON = value;
					this.SendPropertyChanged("freeze_UPDATEDON");
					this.Onfreeze_UPDATEDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_ECUNAME", DbType="NVarChar(500)")]
		public string freeze_ECUNAME
		{
			get
			{
				return this._freeze_ECUNAME;
			}
			set
			{
				if ((this._freeze_ECUNAME != value))
				{
					this.Onfreeze_ECUNAMEChanging(value);
					this.SendPropertyChanging();
					this._freeze_ECUNAME = value;
					this.SendPropertyChanged("freeze_ECUNAME");
					this.Onfreeze_ECUNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_VEHICLENAME", DbType="NVarChar(500)")]
		public string freeze_VEHICLENAME
		{
			get
			{
				return this._freeze_VEHICLENAME;
			}
			set
			{
				if ((this._freeze_VEHICLENAME != value))
				{
					this.Onfreeze_VEHICLENAMEChanging(value);
					this.SendPropertyChanging();
					this._freeze_VEHICLENAME = value;
					this.SendPropertyChanged("freeze_VEHICLENAME");
					this.Onfreeze_VEHICLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_LOGINID", DbType="NVarChar(50)")]
		public string freeze_LOGINID
		{
			get
			{
				return this._freeze_LOGINID;
			}
			set
			{
				if ((this._freeze_LOGINID != value))
				{
					this.Onfreeze_LOGINIDChanging(value);
					this.SendPropertyChanging();
					this._freeze_LOGINID = value;
					this.SendPropertyChanged("freeze_LOGINID");
					this.Onfreeze_LOGINIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_LOGINNAME", DbType="NVarChar(50)")]
		public string freeze_LOGINNAME
		{
			get
			{
				return this._freeze_LOGINNAME;
			}
			set
			{
				if ((this._freeze_LOGINNAME != value))
				{
					this.Onfreeze_LOGINNAMEChanging(value);
					this.SendPropertyChanging();
					this._freeze_LOGINNAME = value;
					this.SendPropertyChanged("freeze_LOGINNAME");
					this.Onfreeze_LOGINNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_MOBILE_MAC_ADDRESS", DbType="NVarChar(50)")]
		public string freeze_MOBILE_MAC_ADDRESS
		{
			get
			{
				return this._freeze_MOBILE_MAC_ADDRESS;
			}
			set
			{
				if ((this._freeze_MOBILE_MAC_ADDRESS != value))
				{
					this.Onfreeze_MOBILE_MAC_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._freeze_MOBILE_MAC_ADDRESS = value;
					this.SendPropertyChanged("freeze_MOBILE_MAC_ADDRESS");
					this.Onfreeze_MOBILE_MAC_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_VCIID", DbType="NVarChar(50)")]
		public string freeze_VCIID
		{
			get
			{
				return this._freeze_VCIID;
			}
			set
			{
				if ((this._freeze_VCIID != value))
				{
					this.Onfreeze_VCIIDChanging(value);
					this.SendPropertyChanging();
					this._freeze_VCIID = value;
					this.SendPropertyChanged("freeze_VCIID");
					this.Onfreeze_VCIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_APP_VERSION", DbType="NChar(10)")]
		public string freeze_APP_VERSION
		{
			get
			{
				return this._freeze_APP_VERSION;
			}
			set
			{
				if ((this._freeze_APP_VERSION != value))
				{
					this.Onfreeze_APP_VERSIONChanging(value);
					this.SendPropertyChanging();
					this._freeze_APP_VERSION = value;
					this.SendPropertyChanged("freeze_APP_VERSION");
					this.Onfreeze_APP_VERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_DEALER_NAME", DbType="NVarChar(500)")]
		public string freeze_DEALER_NAME
		{
			get
			{
				return this._freeze_DEALER_NAME;
			}
			set
			{
				if ((this._freeze_DEALER_NAME != value))
				{
					this.Onfreeze_DEALER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._freeze_DEALER_NAME = value;
					this.SendPropertyChanged("freeze_DEALER_NAME");
					this.Onfreeze_DEALER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_AREA", DbType="NVarChar(500)")]
		public string freeze_AREA
		{
			get
			{
				return this._freeze_AREA;
			}
			set
			{
				if ((this._freeze_AREA != value))
				{
					this.Onfreeze_AREAChanging(value);
					this.SendPropertyChanging();
					this._freeze_AREA = value;
					this.SendPropertyChanged("freeze_AREA");
					this.Onfreeze_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_LOCATION", DbType="NVarChar(500)")]
		public string freeze_LOCATION
		{
			get
			{
				return this._freeze_LOCATION;
			}
			set
			{
				if ((this._freeze_LOCATION != value))
				{
					this.Onfreeze_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._freeze_LOCATION = value;
					this.SendPropertyChanged("freeze_LOCATION");
					this.Onfreeze_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_SOURCE", DbType="NVarChar(50)")]
		public string freeze_SOURCE
		{
			get
			{
				return this._freeze_SOURCE;
			}
			set
			{
				if ((this._freeze_SOURCE != value))
				{
					this.Onfreeze_SOURCEChanging(value);
					this.SendPropertyChanging();
					this._freeze_SOURCE = value;
					this.SendPropertyChanged("freeze_SOURCE");
					this.Onfreeze_SOURCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_ODOValue", DbType="NVarChar(50)")]
		public string freeze_ODOValue
		{
			get
			{
				return this._freeze_ODOValue;
			}
			set
			{
				if ((this._freeze_ODOValue != value))
				{
					this.Onfreeze_ODOValueChanging(value);
					this.SendPropertyChanging();
					this._freeze_ODOValue = value;
					this.SendPropertyChanged("freeze_ODOValue");
					this.Onfreeze_ODOValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_PUSH_NOTIFY", DbType="Bit")]
		public System.Nullable<bool> freeze_PUSH_NOTIFY
		{
			get
			{
				return this._freeze_PUSH_NOTIFY;
			}
			set
			{
				if ((this._freeze_PUSH_NOTIFY != value))
				{
					this.Onfreeze_PUSH_NOTIFYChanging(value);
					this.SendPropertyChanging();
					this._freeze_PUSH_NOTIFY = value;
					this.SendPropertyChanged("freeze_PUSH_NOTIFY");
					this.Onfreeze_PUSH_NOTIFYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeze_NOTIFY_COUNTER", DbType="Int")]
		public System.Nullable<int> freeze_NOTIFY_COUNTER
		{
			get
			{
				return this._freeze_NOTIFY_COUNTER;
			}
			set
			{
				if ((this._freeze_NOTIFY_COUNTER != value))
				{
					this.Onfreeze_NOTIFY_COUNTERChanging(value);
					this.SendPropertyChanging();
					this._freeze_NOTIFY_COUNTER = value;
					this.SendPropertyChanged("freeze_NOTIFY_COUNTER");
					this.Onfreeze_NOTIFY_COUNTERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_CRITICAL_DTC_ADD")]
	public partial class tab_CA_CRITICAL_DTC_ADD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _crt_DTC_PK;
		
		private string _crt_DTC_CODE;
		
		private bool _crt_DTC_STATUS;
		
		private string _crt_DTC_THRESHOLD;
		
		private string _crt_DTC_TYPE;
		
		private string _crt_ECU_NAME;
		
		private string _crt_PLATFORM_NAME;
		
		private string _crt_TYPE_OF_OPERATION;
		
		private System.Nullable<bool> _crt_INVERT_OPERATON;
		
		private string _crt_TYPE_OF_LOGIC;
		
		private System.Nullable<bool> _crt_ISCRITICAL;
		
		private System.DateTime _crt_DTC_CREATED_ON;
		
		private System.Nullable<System.DateTime> _crt_DTC_INACTIVE_ON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncrt_DTC_PKChanging(int value);
    partial void Oncrt_DTC_PKChanged();
    partial void Oncrt_DTC_CODEChanging(string value);
    partial void Oncrt_DTC_CODEChanged();
    partial void Oncrt_DTC_STATUSChanging(bool value);
    partial void Oncrt_DTC_STATUSChanged();
    partial void Oncrt_DTC_THRESHOLDChanging(string value);
    partial void Oncrt_DTC_THRESHOLDChanged();
    partial void Oncrt_DTC_TYPEChanging(string value);
    partial void Oncrt_DTC_TYPEChanged();
    partial void Oncrt_ECU_NAMEChanging(string value);
    partial void Oncrt_ECU_NAMEChanged();
    partial void Oncrt_PLATFORM_NAMEChanging(string value);
    partial void Oncrt_PLATFORM_NAMEChanged();
    partial void Oncrt_TYPE_OF_OPERATIONChanging(string value);
    partial void Oncrt_TYPE_OF_OPERATIONChanged();
    partial void Oncrt_INVERT_OPERATONChanging(System.Nullable<bool> value);
    partial void Oncrt_INVERT_OPERATONChanged();
    partial void Oncrt_TYPE_OF_LOGICChanging(string value);
    partial void Oncrt_TYPE_OF_LOGICChanged();
    partial void Oncrt_ISCRITICALChanging(System.Nullable<bool> value);
    partial void Oncrt_ISCRITICALChanged();
    partial void Oncrt_DTC_CREATED_ONChanging(System.DateTime value);
    partial void Oncrt_DTC_CREATED_ONChanged();
    partial void Oncrt_DTC_INACTIVE_ONChanging(System.Nullable<System.DateTime> value);
    partial void Oncrt_DTC_INACTIVE_ONChanged();
    #endregion
		
		public tab_CA_CRITICAL_DTC_ADD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int crt_DTC_PK
		{
			get
			{
				return this._crt_DTC_PK;
			}
			set
			{
				if ((this._crt_DTC_PK != value))
				{
					this.Oncrt_DTC_PKChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_PK = value;
					this.SendPropertyChanged("crt_DTC_PK");
					this.Oncrt_DTC_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string crt_DTC_CODE
		{
			get
			{
				return this._crt_DTC_CODE;
			}
			set
			{
				if ((this._crt_DTC_CODE != value))
				{
					this.Oncrt_DTC_CODEChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_CODE = value;
					this.SendPropertyChanged("crt_DTC_CODE");
					this.Oncrt_DTC_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_STATUS", DbType="Bit NOT NULL")]
		public bool crt_DTC_STATUS
		{
			get
			{
				return this._crt_DTC_STATUS;
			}
			set
			{
				if ((this._crt_DTC_STATUS != value))
				{
					this.Oncrt_DTC_STATUSChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_STATUS = value;
					this.SendPropertyChanged("crt_DTC_STATUS");
					this.Oncrt_DTC_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_THRESHOLD", DbType="NVarChar(50)")]
		public string crt_DTC_THRESHOLD
		{
			get
			{
				return this._crt_DTC_THRESHOLD;
			}
			set
			{
				if ((this._crt_DTC_THRESHOLD != value))
				{
					this.Oncrt_DTC_THRESHOLDChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_THRESHOLD = value;
					this.SendPropertyChanged("crt_DTC_THRESHOLD");
					this.Oncrt_DTC_THRESHOLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_TYPE", DbType="NVarChar(150)")]
		public string crt_DTC_TYPE
		{
			get
			{
				return this._crt_DTC_TYPE;
			}
			set
			{
				if ((this._crt_DTC_TYPE != value))
				{
					this.Oncrt_DTC_TYPEChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_TYPE = value;
					this.SendPropertyChanged("crt_DTC_TYPE");
					this.Oncrt_DTC_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_ECU_NAME", DbType="NVarChar(100)")]
		public string crt_ECU_NAME
		{
			get
			{
				return this._crt_ECU_NAME;
			}
			set
			{
				if ((this._crt_ECU_NAME != value))
				{
					this.Oncrt_ECU_NAMEChanging(value);
					this.SendPropertyChanging();
					this._crt_ECU_NAME = value;
					this.SendPropertyChanged("crt_ECU_NAME");
					this.Oncrt_ECU_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_PLATFORM_NAME", DbType="NVarChar(100)")]
		public string crt_PLATFORM_NAME
		{
			get
			{
				return this._crt_PLATFORM_NAME;
			}
			set
			{
				if ((this._crt_PLATFORM_NAME != value))
				{
					this.Oncrt_PLATFORM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._crt_PLATFORM_NAME = value;
					this.SendPropertyChanged("crt_PLATFORM_NAME");
					this.Oncrt_PLATFORM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_TYPE_OF_OPERATION", DbType="NVarChar(50)")]
		public string crt_TYPE_OF_OPERATION
		{
			get
			{
				return this._crt_TYPE_OF_OPERATION;
			}
			set
			{
				if ((this._crt_TYPE_OF_OPERATION != value))
				{
					this.Oncrt_TYPE_OF_OPERATIONChanging(value);
					this.SendPropertyChanging();
					this._crt_TYPE_OF_OPERATION = value;
					this.SendPropertyChanged("crt_TYPE_OF_OPERATION");
					this.Oncrt_TYPE_OF_OPERATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_INVERT_OPERATON", DbType="Bit")]
		public System.Nullable<bool> crt_INVERT_OPERATON
		{
			get
			{
				return this._crt_INVERT_OPERATON;
			}
			set
			{
				if ((this._crt_INVERT_OPERATON != value))
				{
					this.Oncrt_INVERT_OPERATONChanging(value);
					this.SendPropertyChanging();
					this._crt_INVERT_OPERATON = value;
					this.SendPropertyChanged("crt_INVERT_OPERATON");
					this.Oncrt_INVERT_OPERATONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_TYPE_OF_LOGIC", DbType="NVarChar(10)")]
		public string crt_TYPE_OF_LOGIC
		{
			get
			{
				return this._crt_TYPE_OF_LOGIC;
			}
			set
			{
				if ((this._crt_TYPE_OF_LOGIC != value))
				{
					this.Oncrt_TYPE_OF_LOGICChanging(value);
					this.SendPropertyChanging();
					this._crt_TYPE_OF_LOGIC = value;
					this.SendPropertyChanged("crt_TYPE_OF_LOGIC");
					this.Oncrt_TYPE_OF_LOGICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_ISCRITICAL", DbType="Bit")]
		public System.Nullable<bool> crt_ISCRITICAL
		{
			get
			{
				return this._crt_ISCRITICAL;
			}
			set
			{
				if ((this._crt_ISCRITICAL != value))
				{
					this.Oncrt_ISCRITICALChanging(value);
					this.SendPropertyChanging();
					this._crt_ISCRITICAL = value;
					this.SendPropertyChanged("crt_ISCRITICAL");
					this.Oncrt_ISCRITICALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_CREATED_ON", DbType="DateTime NOT NULL")]
		public System.DateTime crt_DTC_CREATED_ON
		{
			get
			{
				return this._crt_DTC_CREATED_ON;
			}
			set
			{
				if ((this._crt_DTC_CREATED_ON != value))
				{
					this.Oncrt_DTC_CREATED_ONChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_CREATED_ON = value;
					this.SendPropertyChanged("crt_DTC_CREATED_ON");
					this.Oncrt_DTC_CREATED_ONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_DTC_INACTIVE_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> crt_DTC_INACTIVE_ON
		{
			get
			{
				return this._crt_DTC_INACTIVE_ON;
			}
			set
			{
				if ((this._crt_DTC_INACTIVE_ON != value))
				{
					this.Oncrt_DTC_INACTIVE_ONChanging(value);
					this.SendPropertyChanging();
					this._crt_DTC_INACTIVE_ON = value;
					this.SendPropertyChanged("crt_DTC_INACTIVE_ON");
					this.Oncrt_DTC_INACTIVE_ONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_EMS_DTC_LOGIC_ADD")]
	public partial class tab_CA_EMS_DTC_LOGIC_ADD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtc_LOGIC_ADD_PK;
		
		private string _dtc_DTC_CODE;
		
		private string _dtc_LOGIC;
		
		private System.Nullable<double> _dtc_LOGIC_THRESHOLD;
		
		private System.Nullable<bool> _dtc_LOGIC_RESULT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondtc_LOGIC_ADD_PKChanging(int value);
    partial void Ondtc_LOGIC_ADD_PKChanged();
    partial void Ondtc_DTC_CODEChanging(string value);
    partial void Ondtc_DTC_CODEChanged();
    partial void Ondtc_LOGICChanging(string value);
    partial void Ondtc_LOGICChanged();
    partial void Ondtc_LOGIC_THRESHOLDChanging(System.Nullable<double> value);
    partial void Ondtc_LOGIC_THRESHOLDChanged();
    partial void Ondtc_LOGIC_RESULTChanging(System.Nullable<bool> value);
    partial void Ondtc_LOGIC_RESULTChanged();
    #endregion
		
		public tab_CA_EMS_DTC_LOGIC_ADD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_ADD_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtc_LOGIC_ADD_PK
		{
			get
			{
				return this._dtc_LOGIC_ADD_PK;
			}
			set
			{
				if ((this._dtc_LOGIC_ADD_PK != value))
				{
					this.Ondtc_LOGIC_ADD_PKChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_ADD_PK = value;
					this.SendPropertyChanged("dtc_LOGIC_ADD_PK");
					this.Ondtc_LOGIC_ADD_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dtc_DTC_CODE
		{
			get
			{
				return this._dtc_DTC_CODE;
			}
			set
			{
				if ((this._dtc_DTC_CODE != value))
				{
					this.Ondtc_DTC_CODEChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE = value;
					this.SendPropertyChanged("dtc_DTC_CODE");
					this.Ondtc_DTC_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string dtc_LOGIC
		{
			get
			{
				return this._dtc_LOGIC;
			}
			set
			{
				if ((this._dtc_LOGIC != value))
				{
					this.Ondtc_LOGICChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC = value;
					this.SendPropertyChanged("dtc_LOGIC");
					this.Ondtc_LOGICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_THRESHOLD", DbType="Float")]
		public System.Nullable<double> dtc_LOGIC_THRESHOLD
		{
			get
			{
				return this._dtc_LOGIC_THRESHOLD;
			}
			set
			{
				if ((this._dtc_LOGIC_THRESHOLD != value))
				{
					this.Ondtc_LOGIC_THRESHOLDChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_THRESHOLD = value;
					this.SendPropertyChanged("dtc_LOGIC_THRESHOLD");
					this.Ondtc_LOGIC_THRESHOLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_RESULT", DbType="Bit")]
		public System.Nullable<bool> dtc_LOGIC_RESULT
		{
			get
			{
				return this._dtc_LOGIC_RESULT;
			}
			set
			{
				if ((this._dtc_LOGIC_RESULT != value))
				{
					this.Ondtc_LOGIC_RESULTChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_RESULT = value;
					this.SendPropertyChanged("dtc_LOGIC_RESULT");
					this.Ondtc_LOGIC_RESULTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_CA_EMS_DTC_LOGIC_BUILD")]
	public partial class tab_CA_EMS_DTC_LOGIC_BUILD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtc_LOGIC_BUILD_PK;
		
		private string _dtc_DTC_CODE_A;
		
		private System.Nullable<bool> _dtc_DTC_CODE_A_INVERT;
		
		private string _dtc_DTC_CODE_B;
		
		private System.Nullable<bool> _dtc_DTC_CODE_B_INVERT;
		
		private string _dtc_DTC_CODE_C;
		
		private System.Nullable<bool> _dtc_DTC_CODE_C_INVERT;
		
		private string _dtc_DTC_CODE_D;
		
		private System.Nullable<bool> _dtc_DTC_CODE_D_INVERT;
		
		private string _dtc_LOGIC_OPERATION;
		
		private string _dtc_LOGIC_CONCLUSION;
		
		private System.Nullable<bool> _dtc_LOGIC_STATUS;
		
		private string _dtc_LOGIC_SMILEY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondtc_LOGIC_BUILD_PKChanging(int value);
    partial void Ondtc_LOGIC_BUILD_PKChanged();
    partial void Ondtc_DTC_CODE_AChanging(string value);
    partial void Ondtc_DTC_CODE_AChanged();
    partial void Ondtc_DTC_CODE_A_INVERTChanging(System.Nullable<bool> value);
    partial void Ondtc_DTC_CODE_A_INVERTChanged();
    partial void Ondtc_DTC_CODE_BChanging(string value);
    partial void Ondtc_DTC_CODE_BChanged();
    partial void Ondtc_DTC_CODE_B_INVERTChanging(System.Nullable<bool> value);
    partial void Ondtc_DTC_CODE_B_INVERTChanged();
    partial void Ondtc_DTC_CODE_CChanging(string value);
    partial void Ondtc_DTC_CODE_CChanged();
    partial void Ondtc_DTC_CODE_C_INVERTChanging(System.Nullable<bool> value);
    partial void Ondtc_DTC_CODE_C_INVERTChanged();
    partial void Ondtc_DTC_CODE_DChanging(string value);
    partial void Ondtc_DTC_CODE_DChanged();
    partial void Ondtc_DTC_CODE_D_INVERTChanging(System.Nullable<bool> value);
    partial void Ondtc_DTC_CODE_D_INVERTChanged();
    partial void Ondtc_LOGIC_OPERATIONChanging(string value);
    partial void Ondtc_LOGIC_OPERATIONChanged();
    partial void Ondtc_LOGIC_CONCLUSIONChanging(string value);
    partial void Ondtc_LOGIC_CONCLUSIONChanged();
    partial void Ondtc_LOGIC_STATUSChanging(System.Nullable<bool> value);
    partial void Ondtc_LOGIC_STATUSChanged();
    partial void Ondtc_LOGIC_SMILEYChanging(string value);
    partial void Ondtc_LOGIC_SMILEYChanged();
    #endregion
		
		public tab_CA_EMS_DTC_LOGIC_BUILD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_BUILD_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtc_LOGIC_BUILD_PK
		{
			get
			{
				return this._dtc_LOGIC_BUILD_PK;
			}
			set
			{
				if ((this._dtc_LOGIC_BUILD_PK != value))
				{
					this.Ondtc_LOGIC_BUILD_PKChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_BUILD_PK = value;
					this.SendPropertyChanged("dtc_LOGIC_BUILD_PK");
					this.Ondtc_LOGIC_BUILD_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_A", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dtc_DTC_CODE_A
		{
			get
			{
				return this._dtc_DTC_CODE_A;
			}
			set
			{
				if ((this._dtc_DTC_CODE_A != value))
				{
					this.Ondtc_DTC_CODE_AChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_A = value;
					this.SendPropertyChanged("dtc_DTC_CODE_A");
					this.Ondtc_DTC_CODE_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_A_INVERT", DbType="Bit")]
		public System.Nullable<bool> dtc_DTC_CODE_A_INVERT
		{
			get
			{
				return this._dtc_DTC_CODE_A_INVERT;
			}
			set
			{
				if ((this._dtc_DTC_CODE_A_INVERT != value))
				{
					this.Ondtc_DTC_CODE_A_INVERTChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_A_INVERT = value;
					this.SendPropertyChanged("dtc_DTC_CODE_A_INVERT");
					this.Ondtc_DTC_CODE_A_INVERTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_B", DbType="NVarChar(50)")]
		public string dtc_DTC_CODE_B
		{
			get
			{
				return this._dtc_DTC_CODE_B;
			}
			set
			{
				if ((this._dtc_DTC_CODE_B != value))
				{
					this.Ondtc_DTC_CODE_BChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_B = value;
					this.SendPropertyChanged("dtc_DTC_CODE_B");
					this.Ondtc_DTC_CODE_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_B_INVERT", DbType="Bit")]
		public System.Nullable<bool> dtc_DTC_CODE_B_INVERT
		{
			get
			{
				return this._dtc_DTC_CODE_B_INVERT;
			}
			set
			{
				if ((this._dtc_DTC_CODE_B_INVERT != value))
				{
					this.Ondtc_DTC_CODE_B_INVERTChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_B_INVERT = value;
					this.SendPropertyChanged("dtc_DTC_CODE_B_INVERT");
					this.Ondtc_DTC_CODE_B_INVERTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_C", DbType="NVarChar(50)")]
		public string dtc_DTC_CODE_C
		{
			get
			{
				return this._dtc_DTC_CODE_C;
			}
			set
			{
				if ((this._dtc_DTC_CODE_C != value))
				{
					this.Ondtc_DTC_CODE_CChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_C = value;
					this.SendPropertyChanged("dtc_DTC_CODE_C");
					this.Ondtc_DTC_CODE_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_C_INVERT", DbType="Bit")]
		public System.Nullable<bool> dtc_DTC_CODE_C_INVERT
		{
			get
			{
				return this._dtc_DTC_CODE_C_INVERT;
			}
			set
			{
				if ((this._dtc_DTC_CODE_C_INVERT != value))
				{
					this.Ondtc_DTC_CODE_C_INVERTChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_C_INVERT = value;
					this.SendPropertyChanged("dtc_DTC_CODE_C_INVERT");
					this.Ondtc_DTC_CODE_C_INVERTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_D", DbType="NVarChar(50)")]
		public string dtc_DTC_CODE_D
		{
			get
			{
				return this._dtc_DTC_CODE_D;
			}
			set
			{
				if ((this._dtc_DTC_CODE_D != value))
				{
					this.Ondtc_DTC_CODE_DChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_D = value;
					this.SendPropertyChanged("dtc_DTC_CODE_D");
					this.Ondtc_DTC_CODE_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_DTC_CODE_D_INVERT", DbType="Bit")]
		public System.Nullable<bool> dtc_DTC_CODE_D_INVERT
		{
			get
			{
				return this._dtc_DTC_CODE_D_INVERT;
			}
			set
			{
				if ((this._dtc_DTC_CODE_D_INVERT != value))
				{
					this.Ondtc_DTC_CODE_D_INVERTChanging(value);
					this.SendPropertyChanging();
					this._dtc_DTC_CODE_D_INVERT = value;
					this.SendPropertyChanged("dtc_DTC_CODE_D_INVERT");
					this.Ondtc_DTC_CODE_D_INVERTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_OPERATION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dtc_LOGIC_OPERATION
		{
			get
			{
				return this._dtc_LOGIC_OPERATION;
			}
			set
			{
				if ((this._dtc_LOGIC_OPERATION != value))
				{
					this.Ondtc_LOGIC_OPERATIONChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_OPERATION = value;
					this.SendPropertyChanged("dtc_LOGIC_OPERATION");
					this.Ondtc_LOGIC_OPERATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_CONCLUSION", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string dtc_LOGIC_CONCLUSION
		{
			get
			{
				return this._dtc_LOGIC_CONCLUSION;
			}
			set
			{
				if ((this._dtc_LOGIC_CONCLUSION != value))
				{
					this.Ondtc_LOGIC_CONCLUSIONChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_CONCLUSION = value;
					this.SendPropertyChanged("dtc_LOGIC_CONCLUSION");
					this.Ondtc_LOGIC_CONCLUSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_STATUS", DbType="Bit")]
		public System.Nullable<bool> dtc_LOGIC_STATUS
		{
			get
			{
				return this._dtc_LOGIC_STATUS;
			}
			set
			{
				if ((this._dtc_LOGIC_STATUS != value))
				{
					this.Ondtc_LOGIC_STATUSChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_STATUS = value;
					this.SendPropertyChanged("dtc_LOGIC_STATUS");
					this.Ondtc_LOGIC_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc_LOGIC_SMILEY", DbType="NVarChar(250)")]
		public string dtc_LOGIC_SMILEY
		{
			get
			{
				return this._dtc_LOGIC_SMILEY;
			}
			set
			{
				if ((this._dtc_LOGIC_SMILEY != value))
				{
					this.Ondtc_LOGIC_SMILEYChanging(value);
					this.SendPropertyChanging();
					this._dtc_LOGIC_SMILEY = value;
					this.SendPropertyChanged("dtc_LOGIC_SMILEY");
					this.Ondtc_LOGIC_SMILEYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_m_ADMIN_USER")]
	public partial class tab_m_ADMIN_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_ID_PK;
		
		private string _user_FIRST_NAME;
		
		private string _user_LAST_NAME;
		
		private bool _user_GENDER;
		
		private short _user_ROLE;
		
		private string _user_EMAIL_ID;
		
		private string _user_CONTACT_NO;
		
		private string _user_ACCESS_CODE;
		
		private string _user_PASSWORD;
		
		private System.Nullable<bool> _user_ACTIVE_STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_ID_PKChanging(int value);
    partial void Onuser_ID_PKChanged();
    partial void Onuser_FIRST_NAMEChanging(string value);
    partial void Onuser_FIRST_NAMEChanged();
    partial void Onuser_LAST_NAMEChanging(string value);
    partial void Onuser_LAST_NAMEChanged();
    partial void Onuser_GENDERChanging(bool value);
    partial void Onuser_GENDERChanged();
    partial void Onuser_ROLEChanging(short value);
    partial void Onuser_ROLEChanged();
    partial void Onuser_EMAIL_IDChanging(string value);
    partial void Onuser_EMAIL_IDChanged();
    partial void Onuser_CONTACT_NOChanging(string value);
    partial void Onuser_CONTACT_NOChanged();
    partial void Onuser_ACCESS_CODEChanging(string value);
    partial void Onuser_ACCESS_CODEChanged();
    partial void Onuser_PASSWORDChanging(string value);
    partial void Onuser_PASSWORDChanged();
    partial void Onuser_ACTIVE_STATUSChanging(System.Nullable<bool> value);
    partial void Onuser_ACTIVE_STATUSChanged();
    #endregion
		
		public tab_m_ADMIN_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ID_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_ID_PK
		{
			get
			{
				return this._user_ID_PK;
			}
			set
			{
				if ((this._user_ID_PK != value))
				{
					this.Onuser_ID_PKChanging(value);
					this.SendPropertyChanging();
					this._user_ID_PK = value;
					this.SendPropertyChanged("user_ID_PK");
					this.Onuser_ID_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_FIRST_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_FIRST_NAME
		{
			get
			{
				return this._user_FIRST_NAME;
			}
			set
			{
				if ((this._user_FIRST_NAME != value))
				{
					this.Onuser_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._user_FIRST_NAME = value;
					this.SendPropertyChanged("user_FIRST_NAME");
					this.Onuser_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_LAST_NAME", DbType="NVarChar(25)")]
		public string user_LAST_NAME
		{
			get
			{
				return this._user_LAST_NAME;
			}
			set
			{
				if ((this._user_LAST_NAME != value))
				{
					this.Onuser_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._user_LAST_NAME = value;
					this.SendPropertyChanged("user_LAST_NAME");
					this.Onuser_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_GENDER", DbType="Bit NOT NULL")]
		public bool user_GENDER
		{
			get
			{
				return this._user_GENDER;
			}
			set
			{
				if ((this._user_GENDER != value))
				{
					this.Onuser_GENDERChanging(value);
					this.SendPropertyChanging();
					this._user_GENDER = value;
					this.SendPropertyChanged("user_GENDER");
					this.Onuser_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ROLE", DbType="SmallInt NOT NULL")]
		public short user_ROLE
		{
			get
			{
				return this._user_ROLE;
			}
			set
			{
				if ((this._user_ROLE != value))
				{
					this.Onuser_ROLEChanging(value);
					this.SendPropertyChanging();
					this._user_ROLE = value;
					this.SendPropertyChanged("user_ROLE");
					this.Onuser_ROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_EMAIL_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_EMAIL_ID
		{
			get
			{
				return this._user_EMAIL_ID;
			}
			set
			{
				if ((this._user_EMAIL_ID != value))
				{
					this.Onuser_EMAIL_IDChanging(value);
					this.SendPropertyChanging();
					this._user_EMAIL_ID = value;
					this.SendPropertyChanged("user_EMAIL_ID");
					this.Onuser_EMAIL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_CONTACT_NO", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string user_CONTACT_NO
		{
			get
			{
				return this._user_CONTACT_NO;
			}
			set
			{
				if ((this._user_CONTACT_NO != value))
				{
					this.Onuser_CONTACT_NOChanging(value);
					this.SendPropertyChanging();
					this._user_CONTACT_NO = value;
					this.SendPropertyChanged("user_CONTACT_NO");
					this.Onuser_CONTACT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ACCESS_CODE", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string user_ACCESS_CODE
		{
			get
			{
				return this._user_ACCESS_CODE;
			}
			set
			{
				if ((this._user_ACCESS_CODE != value))
				{
					this.Onuser_ACCESS_CODEChanging(value);
					this.SendPropertyChanging();
					this._user_ACCESS_CODE = value;
					this.SendPropertyChanged("user_ACCESS_CODE");
					this.Onuser_ACCESS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_PASSWORD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string user_PASSWORD
		{
			get
			{
				return this._user_PASSWORD;
			}
			set
			{
				if ((this._user_PASSWORD != value))
				{
					this.Onuser_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._user_PASSWORD = value;
					this.SendPropertyChanged("user_PASSWORD");
					this.Onuser_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ACTIVE_STATUS", DbType="Bit")]
		public System.Nullable<bool> user_ACTIVE_STATUS
		{
			get
			{
				return this._user_ACTIVE_STATUS;
			}
			set
			{
				if ((this._user_ACTIVE_STATUS != value))
				{
					this.Onuser_ACTIVE_STATUSChanging(value);
					this.SendPropertyChanging();
					this._user_ACTIVE_STATUS = value;
					this.SendPropertyChanged("user_ACTIVE_STATUS");
					this.Onuser_ACTIVE_STATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_m_VIN_SCORE")]
	public partial class tab_m_VIN_SCORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Leader_ID_PK;
		
		private string _Leader_Name;
		
		private string _Leader_VIN_NUMBER;
		
		private System.DateTime _Leader_TIMESTAMP;
		
		private decimal _Leader_SCORE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLeader_ID_PKChanging(long value);
    partial void OnLeader_ID_PKChanged();
    partial void OnLeader_NameChanging(string value);
    partial void OnLeader_NameChanged();
    partial void OnLeader_VIN_NUMBERChanging(string value);
    partial void OnLeader_VIN_NUMBERChanged();
    partial void OnLeader_TIMESTAMPChanging(System.DateTime value);
    partial void OnLeader_TIMESTAMPChanged();
    partial void OnLeader_SCOREChanging(decimal value);
    partial void OnLeader_SCOREChanged();
    #endregion
		
		public tab_m_VIN_SCORE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leader_ID_PK", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Leader_ID_PK
		{
			get
			{
				return this._Leader_ID_PK;
			}
			set
			{
				if ((this._Leader_ID_PK != value))
				{
					this.OnLeader_ID_PKChanging(value);
					this.SendPropertyChanging();
					this._Leader_ID_PK = value;
					this.SendPropertyChanged("Leader_ID_PK");
					this.OnLeader_ID_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leader_Name", DbType="NVarChar(100)")]
		public string Leader_Name
		{
			get
			{
				return this._Leader_Name;
			}
			set
			{
				if ((this._Leader_Name != value))
				{
					this.OnLeader_NameChanging(value);
					this.SendPropertyChanging();
					this._Leader_Name = value;
					this.SendPropertyChanged("Leader_Name");
					this.OnLeader_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leader_VIN_NUMBER", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Leader_VIN_NUMBER
		{
			get
			{
				return this._Leader_VIN_NUMBER;
			}
			set
			{
				if ((this._Leader_VIN_NUMBER != value))
				{
					this.OnLeader_VIN_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._Leader_VIN_NUMBER = value;
					this.SendPropertyChanged("Leader_VIN_NUMBER");
					this.OnLeader_VIN_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leader_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime Leader_TIMESTAMP
		{
			get
			{
				return this._Leader_TIMESTAMP;
			}
			set
			{
				if ((this._Leader_TIMESTAMP != value))
				{
					this.OnLeader_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._Leader_TIMESTAMP = value;
					this.SendPropertyChanged("Leader_TIMESTAMP");
					this.OnLeader_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leader_SCORE", DbType="Decimal(18,0) NOT NULL")]
		public decimal Leader_SCORE
		{
			get
			{
				return this._Leader_SCORE;
			}
			set
			{
				if ((this._Leader_SCORE != value))
				{
					this.OnLeader_SCOREChanging(value);
					this.SendPropertyChanging();
					this._Leader_SCORE = value;
					this.SendPropertyChanged("Leader_SCORE");
					this.OnLeader_SCOREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
